*Will turn these into functions that will standardize names
cap program drop standardize_bookrunners
program define standardize_bookrunners
	replace bookrunners = subinstr(bookrunners,",","",.)
	replace bookrunners = subinstr(bookrunners,"(JB)","",.)
	*Remove some common suffixes, then eventually turn to lowercase
	replace bookrunners = subinstr(bookrunners,"-CAPITAL","",.)
	replace bookrunners = subinstr(bookrunners,"-CAP","",.)
	replace bookrunners = subinstr(bookrunners,"-GROUP","",.)
	replace bookrunners = subinstr(bookrunners,"-PLC","",.)
	replace bookrunners = subinstr(bookrunners,"-SECURITIES","",.)
	replace bookrunners = subinstr(bookrunners,"-SEC","",.)
	replace bookrunners = subinstr(bookrunners,"-UK","",.)
	replace bookrunners = subinstr(bookrunners,"-GR","",.)
	replace bookrunners = subinstr(bookrunners,"-EURO","",.)
	replace bookrunners = subinstr(bookrunners,"-PARTNER","",.)
	replace bookrunners = subinstr(bookrunners,"-PTNRS","",.)
	replace bookrunners = subinstr(bookrunners,"-LLC","",.)
	replace bookrunners = subinstr(bookrunners,"-LTD","",.)
	replace bookrunners = subinstr(bookrunners,"-FINANCIAL","",.)
	replace bookrunners = subinstr(bookrunners,"-FIN","",.)
	replace bookrunners = subinstr(bookrunners,"-CORP","",.)
	replace bookrunners = subinstr(bookrunners,"-CO","",.)
	replace bookrunners = subinstr(bookrunners,"-INC","",.)
	replace bookrunners = subinstr(bookrunners,"-INV","",.)
	replace bookrunners = subinstr(bookrunners,"-US","",.)
	replace bookrunners = subinstr(bookrunners,"-AG","",.)
	replace bookrunners = subinstr(bookrunners,"-AUS","",.)
	replace bookrunners = subinstr(bookrunners,"-INTL","",.)
	replace bookrunners = subinstr(bookrunners,"-INT","",.)
	replace bookrunners = subinstr(bookrunners,"-HK","",.)
	replace bookrunners = subinstr(bookrunners,"-AU","",.)
	replace bookrunners = subinstr(bookrunners,"-MKT","",.)
	replace bookrunners = subinstr(bookrunners,"-GRP","",.)
	replace bookrunners = subinstr(bookrunners,"-BANK","",.)
	replace bookrunners = subinstr(bookrunners,"-BNK","",.)
	replace bookrunners = subinstr(bookrunners,"-BK","",.)
	replace bookrunners = subinstr(bookrunners,"-GRP","",.)
	replace bookrunners = subinstr(bookrunners,"-LP","",.)
	replace bookrunners = subinstr(bookrunners,"-MARKETS","",.)
	replace bookrunners = subinstr(bookrunners,"-NY","",.)
	replace bookrunners = subinstr(bookrunners,"-HQ","",.)
	replace bookrunners = subinstr(bookrunners,"-I","",.)
	replace bookrunners = subinstr(bookrunners,"-"," ",.)
	replace bookrunners = subinstr(bookrunners,"_"," ",.)
	replace bookrunners = subinstr(bookrunners," GIBRALTOR"," ",.)
	replace bookrunners = subinstr(bookrunners," CA"," ",.)	
	replace bookrunners = subinstr(bookrunners," PVT"," ",.)
	replace bookrunners = subinstr(bookrunners," LLP"," ",.)
	replace bookrunners = subinstr(bookrunners," ASIA"," ",.)
	replace bookrunners = subinstr(bookrunners," VK"," ",.)
	replace bookrunners = subinstr(bookrunners," NV"," ",.)
	replace bookrunners = subinstr(bookrunners," FS"," ",.)
	replace bookrunners = subinstr(bookrunners," OKLAHOMA"," ",.)
	replace bookrunners = subinstr(bookrunners," ST LOUIS"," ",.)
	replace bookrunners = subinstr(bookrunners," STL"," ",.)
	replace bookrunners = subinstr(bookrunners," TR"," ",.)
	replace bookrunners = subinstr(bookrunners," TW"," ",.)
	replace bookrunners = subinstr(bookrunners," MI"," ",.)
	replace bookrunners = subinstr(bookrunners," MISSOURI"," ",.)
	replace bookrunners = subinstr(bookrunners," ASSOC"," ",.)
	replace bookrunners = subinstr(bookrunners," CT"," ",.)
	replace bookrunners = subinstr(bookrunners," FL"," ",.)
	replace bookrunners = subinstr(bookrunners," GE"," ",.)
	replace bookrunners = subinstr(bookrunners," NB"," ",.)
	replace bookrunners = subinstr(bookrunners," NC"," ",.)
	replace bookrunners = subinstr(bookrunners," VA"," ",.)	
	replace bookrunners = subinstr(bookrunners," CM"," ",.)	
	replace bookrunners = subinstr(bookrunners," TAIWAN"," ",.)	
	replace bookrunners = subinstr(bookrunners," CM"," ",.)	
	replace bookrunners = subinstr(bookrunners," TX"," ",.)		
	replace bookrunners = subinstr(bookrunners," KS"," ",.)		
	replace bookrunners = subinstr(bookrunners," TAIPEI"," ",.)		
	replace bookrunners = subinstr(bookrunners," UST AM"," ",.)		
	replace bookrunners = subinstr(bookrunners," LONDON"," ",.)		
	replace bookrunners = subinstr(bookrunners," TOKYO"," ",.)		
	replace bookrunners = subinstr(bookrunners," UST"," ",.)		
	replace bookrunners = subinstr(bookrunners," NA"," ",.)		
	
	*Now make them proper case
	replace bookrunners = proper(bookrunners)
	*Now standardize them
	replace bookrunners = subinstr(bookrunners,"Dlj","Donaldson Lufkin & Jenrette",.)
	replace bookrunners = subinstr(bookrunners,"Salomon Smith","Salomon Smith Barney",.)
	replace bookrunners = subinstr(bookrunners,"Merrill","Merrill Lynch",.)
	replace bookrunners = subinstr(bookrunners,"Cs Fb Cs","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Cs Fb","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Deutsche Alex B","Deutsche Bank",.)
	replace bookrunners = subinstr(bookrunners,"Csfb","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Cibc World","CIBC",.)
	replace bookrunners = subinstr(bookrunners,"Leh","Lehman Brothers",.)
	replace bookrunners = subinstr(bookrunners,"Jpmch","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jpmp","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jpml","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jpm","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Ml","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Msdw","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Bear","Bear Stearns",.)
	replace bookrunners = subinstr(bookrunners,"Psi","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"Cowen","Societe Generale",.)
	replace bookrunners = subinstr(bookrunners,"Friedman B","FBR",.)
	replace bookrunners = subinstr(bookrunners,"Hambrecht","Hambrecht & Quist",.)
	replace bookrunners = subinstr(bookrunners,"Ing Barings","ING",.)
	replace bookrunners = subinstr(bookrunners,"Warburg Dr","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Wdr","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Sutro","Sutro & Co",.)
	replace bookrunners = subinstr(bookrunners,"Us Piper","US Bancorp",.)
	replace bookrunners = subinstr(bookrunners,"Ubs Warburg","UBS",.)
	replace bookrunners = subinstr(bookrunners,"A G Edwards","A.G. Edwards",.)
	replace bookrunners = subinstr(bookrunners,"Adams Harkness","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Brous","HD Brous",.)
	replace bookrunners = subinstr(bookrunners,"Boston Roberts","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Gunnar","Joseph Gunnar",.)
	replace bookrunners = subinstr(bookrunners,"C S F B","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Kashner","Kashner Davidson",.)
	replace bookrunners = subinstr(bookrunners,"Fleet Rob Steph","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Prud Volpe","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"Pru Vec Hc","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"To Be Announced","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Mcdonald","McDonald",.)
	replace bookrunners = subinstr(bookrunners,"Robertson S","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Neidiger","NTB Financial",.)
	replace bookrunners = subinstr(bookrunners,"Wit Soundview","Charles Schwab",.)
	replace bookrunners = subinstr(bookrunners,"Inst Equity","Institutional Equity",.)
	replace bookrunners = subinstr(bookrunners,"H C Wainwright","HC Wainwright",.)
	replace bookrunners = subinstr(bookrunners,"Paulson","Paulson Investment",.)
	replace bookrunners = subinstr(bookrunners,"Warburg","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Paine W","Paine Webber",.)
	replace bookrunners = subinstr(bookrunners,"Penn Mer","PMG Capital",.)
	replace bookrunners = subinstr(bookrunners,"Robinson","Truist",.)
	replace bookrunners = subinstr(bookrunners,"Starr","Starr Securities",.)
	replace bookrunners = subinstr(bookrunners,"Dain R Wessels","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Hwnt","Hornblower & Weeks",.)
	replace bookrunners = subinstr(bookrunners,"Notapp","NA",.)
	replace bookrunners = subinstr(bookrunners,"Fahnestock","Oppenheimer",.)
	replace bookrunners = subinstr(bookrunners,"Burnham","Burnham Securities",.)
	replace bookrunners = subinstr(bookrunners,"Dg","DZ Bank",.)
	replace bookrunners = subinstr(bookrunners,"Fbsi","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Not Available","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Pru Vec Hc","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"Bb T Cap","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"First Union","Wells Fargo",.)
	replace bookrunners = subinstr(bookrunners,"Csmsc","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Csa","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Deutsche A","Deutsche Bank",.)
	replace bookrunners = subinstr(bookrunners,"Van Kasper","Wells Fargo",.)
	replace bookrunners = subinstr(bookrunners,"Schneider","Schneider Securities",.)
	replace bookrunners = subinstr(bookrunners,"Sandler Oneill","Sandler O'Neill",.)
	replace bookrunners = subinstr(bookrunners,"Coneff","Concord",.)
	replace bookrunners = subinstr(bookrunners,"Morgan Keegan","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Somerset","Somerset Financial",.)
	replace bookrunners = subinstr(bookrunners,"Raymond James Ca","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Calaz","Credit Agricole",.)
	replace bookrunners = subinstr(bookrunners,"Tucker","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Wm Blair","William Blair",.)
	replace bookrunners = subinstr(bookrunners,"Centex","Centex Securities",.)
	replace bookrunners = subinstr(bookrunners,"Unspecified","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Mdb","MDB Capital",.)
	replace bookrunners = subinstr(bookrunners,"Williams","Investec",.)
	replace bookrunners = subinstr(bookrunners,"Whale","Whale Securities",.)
	replace bookrunners = subinstr(bookrunners,"Mercer Part","Mercer",.)
	replace bookrunners = subinstr(bookrunners,"Abn Amro","ABN AMRO",.)
	replace bookrunners = subinstr(bookrunners,"Abn Rothschild","ABN AMRO",.)
	replace bookrunners = subinstr(bookrunners,"ABN AMRO ","ABN AMRO",.)
	replace bookrunners = subinstr(bookrunners,"ABN AMRO Gov","ABN AMRO",.)
	replace bookrunners = subinstr(bookrunners,"Ag Edwards","AG Edwards",.)
	replace bookrunners = subinstr(bookrunners,"A.G. Edwards","AG Edwards",.)
	replace bookrunners = subinstr(bookrunners,"Adsm","Adam Smith Institute",.)
	replace bookrunners = subinstr(bookrunners,"Aps","APS",.)
	replace bookrunners = subinstr(bookrunners,"Atcapi","Atlas",.)
	replace bookrunners = subinstr(bookrunners,"B Riley Fbr","Merrill Lynch",.)
	replace bookrunners = subinstr(bookrunners,"Bathgate Mccoll","Bathgate",.)
	replace bookrunners = subinstr(bookrunners,"Bb T","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Bk Berlin","Berliner Handels",.)
	replace bookrunners = subinstr(bookrunners,"Bkrs Wi","Bankers Bank of Wisconsin",.)
	replace bookrunners = subinstr(bookrunners,"Bmo Nesbitt","BMO",.)
	replace bookrunners = subinstr(bookrunners,"Bmo Nes","BMO",.)
	replace bookrunners = subinstr(bookrunners,"Bmo","BMO",.)
	replace bookrunners = subinstr(bookrunners,"Bnp Paribas","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"Bnparf","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"Boa Merrill Lynch","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bofa","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Breanmur Carret","Brean",.)
	replace bookrunners = subinstr(bookrunners,"Bsi","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Burnham Securities Hill","Burnham Securities",.)
	replace bookrunners = subinstr(bookrunners,"Btig","BTIG",.)
	replace bookrunners = subinstr(bookrunners,"Can Adams","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Can Fitz","Cantor",.)
	replace bookrunners = subinstr(bookrunners,"Cant Fitz","Cantor",.)
	replace bookrunners = subinstr(bookrunners,"Can Genuity","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Canaccord Gen","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Cdc","CDC",.)
	replace bookrunners = subinstr(bookrunners,"Cgf","CGF",.)
	replace bookrunners = subinstr(bookrunners,"Cibc","CIBC",.)
	replace bookrunners = subinstr(bookrunners,"Citigroup","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citgrp","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citi Gm","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citi Ssb","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Cs Hk","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Ckop","CK Cooper",.)
	replace bookrunners = subinstr(bookrunners,"Chinatrustmm","Chinatrust",.)
	replace bookrunners = subinstr(bookrunners,"Clsa HK","CLSA",.)
	replace bookrunners = subinstr(bookrunners,"Clsa Equity","CLSA",.)
	replace bookrunners = subinstr(bookrunners,"Dnb Nor","DNB",.)
	replace bookrunners = subinstr(bookrunners,"Dnb","DNB",.)
	replace bookrunners = subinstr(bookrunners,"Ed Jones","Edward Jones",.)
	replace bookrunners = subinstr(bookrunners,"Ekn","EKN",.)
	replace bookrunners = subinstr(bookrunners,"Empire Asset","Empire",.)
	replace bookrunners = subinstr(bookrunners,"Ev Distributors","Eaton Vance",.)
	replace bookrunners = subinstr(bookrunners,"Fantex B","Fantex",.)
	replace bookrunners = subinstr(bookrunners,"Fbr","FBR",.)
	replace bookrunners = subinstr(bookrunners,"Figs","Fig",.)
	replace bookrunners = subinstr(bookrunners,"First Dun","First Dunbar",.)
	replace bookrunners = subinstr(bookrunners,"Forbes Pcg","Forbes",.)
	replace bookrunners = subinstr(bookrunners,"Ftn Midwest","FTN Midwest",.)
	replace bookrunners = subinstr(bookrunners,"Gbs Ventures","GBS Ventures",.)
	replace bookrunners = subinstr(bookrunners,"Genuity","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Gmp","GMP",.)
	replace bookrunners = subinstr(bookrunners,"Great Am Adv","Great American Adventures",.)
	replace bookrunners = subinstr(bookrunners,"Griffin Kubik","Griffin",.)
	replace bookrunners = subinstr(bookrunners,"J P Morgan","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jf Mackie","JF Mackie",.)
	replace bookrunners = subinstr(bookrunners,"Jmp","JMP",.)
	replace bookrunners = subinstr(bookrunners,"Jp","JP Carey",.)
	replace bookrunners = subinstr(bookrunners,"Kbc_Peel_Hunt","KBC Peel Hunt",.)
	replace bookrunners = subinstr(bookrunners,"Key Banc","Keybanc",.)
	replace bookrunners = subinstr(bookrunners,"Kgi Tw","KGI",.)
	replace bookrunners = subinstr(bookrunners,"Kkr","KKR",.)
	replace bookrunners = subinstr(bookrunners,"Ms","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Macquarie Ca","Macquarie",.)
	replace bookrunners = subinstr(bookrunners,"Mizuhoa","Mizuho",.)
	replace bookrunners = subinstr(bookrunners,"Morgan Stanley Canada","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Natl","National",.)
	replace bookrunners = subinstr(bookrunners,"National City","National",.)
	replace bookrunners = subinstr(bookrunners,"Nd","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Newport C","Newport Coast",.)
	replace bookrunners = subinstr(bookrunners,"Nobleer","Noble",.)
	replace bookrunners = subinstr(bookrunners,"Northland Cp","Northland",.)	
	replace bookrunners = subinstr(bookrunners,"Non Underwritte","NA",.)
	replace bookrunners = subinstr(bookrunners,"Piper Jaffrey","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Piper J","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Piper Muni","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Pmg","PMG",.)
	replace bookrunners = subinstr(bookrunners,"Pryorunts","Pryor Counts",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Cm","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Cs","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Dain","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Dom","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbcs","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rayjam","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Scot String","Scott String",.)
	replace bookrunners = subinstr(bookrunners,"Sgwen","Cowen",.)
	replace bookrunners = subinstr(bookrunners,"Shinhanr","Shinhan",.)
	replace bookrunners = subinstr(bookrunners,"Ssec","Sunrise",.)
	replace bookrunners = subinstr(bookrunners,"Sterneee","Sterne",.)
	replace bookrunners = subinstr(bookrunners,"Suntrust Rh","Suntrust",.)
	replace bookrunners = subinstr(bookrunners,"Svb Leerink","SVB Leerink",.)
	replace bookrunners = subinstr(bookrunners,"Ubs","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Invbnk","Investec",.)

	replace bookrunners = subinstr(bookrunners,"Bacabv","Bank Austria",.)
	replace bookrunners = subinstr(bookrunners,"Bocia","BOCI",.)
	replace bookrunners = subinstr(bookrunners,"Boci","BOCI",.)
	replace bookrunners = subinstr(bookrunners,"Investecest","Investec",.)
	replace bookrunners = subinstr(bookrunners,"Mufj Morgan Stanley","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Wedbush M ","Wedbush",.)
	replace bookrunners = subinstr(bookrunners,"UBS Pincus","UBS",.)
	replace bookrunners = subinstr(bookrunners,"UBSau","UBS",.)
	replace bookrunners = subinstr(bookrunners,"UBSb","UBS",.)
	replace bookrunners = subinstr(bookrunners,"UBSec Pincus","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Nationalt","National",.)
	replace bookrunners = subinstr(bookrunners,"Lehman Brothersman","Lehman Brothers",.)
	replace bookrunners = subinstr(bookrunners,"JP Morgan Chase","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Banc One","Bank One",.)
	replace bookrunners = subinstr(bookrunners,"Salomon Smith Bank of Americarney","Salomon Smith Barney",.)
	replace bookrunners = subinstr(bookrunners,"Wedbush M","Wedbush",.)
	replace bookrunners = subinstr(bookrunners,"Piper Jaffray","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Aon Ben","Aon",.)
	replace bookrunners = subinstr(bookrunners,"Aons","Aon",.)
	replace bookrunners = subinstr(bookrunners,"BB&T Wind","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Banc America","Bank of America",.)	
	replace bookrunners = subinstr(bookrunners,"Bbt ","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Bbt$","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Bbt","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Bbt","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Bk One","Bank One",.)
	replace bookrunners = subinstr(bookrunners,"Bankone","Bank One",.)
	replace bookrunners = subinstr(bookrunners,"Blaylock Beal","Blaylock",.)
	replace bookrunners = subinstr(bookrunners,"Blaylock N","Blaylock",.)
	replace bookrunners = subinstr(bookrunners,"Blaylock Ptrns","Blaylock",.)
	replace bookrunners = subinstr(bookrunners,"Blaylock Rv","Blaylock",.)
	replace bookrunners = subinstr(bookrunners,"Bnp ","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"Bnp","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"Bny Mellon","BONY",.)
	replace bookrunners = subinstr(bookrunners,"Bny Serv","BONY",.)
	replace bookrunners = subinstr(bookrunners,"Bny","BONY",.)
	replace bookrunners = subinstr(bookrunners,"Bonycm","BONY",.)
	replace bookrunners = subinstr(bookrunners,"Boa","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Boaarg","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bocml","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bstcos","Bear Stearns",.)
	replace bookrunners = subinstr(bookrunners,"Bosc Muni","Bosc",.)
	replace bookrunners = subinstr(bookrunners,"CIBCa","CIBC",.)
	replace bookrunners = subinstr(bookrunners,"Citi Globmkt 2","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citi Globmkt","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citibank","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citigrpgms","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citip","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citis","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Comm Pa","Commerce",.)
	replace bookrunners = subinstr(bookrunners,"Commerce B Muni","Commerce",.)
	replace bookrunners = subinstr(bookrunners,"Commercel","Commerce",.)
	replace bookrunners = subinstr(bookrunners,"Comms","Commerce",.)
	replace bookrunners = subinstr(bookrunners,"Comma","Community Bank",.)
	replace bookrunners = subinstr(bookrunners,"Cred Lyonnais","Credit Lyonnais",.)
	replace bookrunners = subinstr(bookrunners,"Creditri Cib","Credit Agricole",.)
	replace bookrunners = subinstr(bookrunners,"Creditricole","Credit Agricole",.)
	replace bookrunners = subinstr(bookrunners,"Crt","CRT",.)
	replace bookrunners = subinstr(bookrunners,"Cs Eur","Credit Suisse",.)	
	replace bookrunners = subinstr(bookrunners,"Cs Holdingsa","Credit Suisse",.)	
	replace bookrunners = subinstr(bookrunners,"Csc","Charles Schwab",.)
	replace bookrunners = subinstr(bookrunners,"Dain Bos","RBC",.)	
	replace bookrunners = subinstr(bookrunners,"Daiwa Amer","Daiwa",.)	
	replace bookrunners = subinstr(bookrunners,"Daiwa Pe","Daiwa",.)	
	replace bookrunners = subinstr(bookrunners,"Daiwa Sb","Daiwa",.)	
	replace bookrunners = subinstr(bookrunners,"Daiwa Smbc Eur","Daiwa",.)	
	replace bookrunners = subinstr(bookrunners,"Daiwa Smbc","Daiwa",.)	
	replace bookrunners = subinstr(bookrunners,"Dbcm","Deutsche Bank",.)	
	replace bookrunners = subinstr(bookrunners,"Depfa Albany","Depfa",.)	
	replace bookrunners = subinstr(bookrunners,"Deutsche Bank of Americank","Deutsche Bank",.)	
	replace bookrunners = subinstr(bookrunners,"Duncan Investec","Duncan",.)	
	replace bookrunners = subinstr(bookrunners,"First Dstate","First Midstate",.)	
	replace bookrunners = subinstr(bookrunners,"First Hor","First Horizon",.)	
	replace bookrunners = subinstr(bookrunners,"Fleet ","Fleet Boston",.)	
	replace bookrunners = subinstr(bookrunners,"Fleet  Boston","Fleet Boston",.)	
	replace bookrunners = subinstr(bookrunners,"First Tn","First Horizon",.)	
	replace bookrunners = subinstr(bookrunners,"Gmac Rfc","GMAC RFC",.)	
	replace bookrunners = subinstr(bookrunners,"Gmacmm","GMAC RFC",.)	
	replace bookrunners = subinstr(bookrunners,"Gmacmmercial","GMAC RFC",.)	
	replace bookrunners = subinstr(bookrunners,"Gmacrf","GMAC RFC",.)	
	replace bookrunners = subinstr(bookrunners,"Goldman Sachs Es","Goldman Sachs",.)	
	replace bookrunners = subinstr(bookrunners,"Gpc","Great Pacific",.)	
	replace bookrunners = subinstr(bookrunners,"Great Pac","Great Pacific",.)	
	replace bookrunners = subinstr(bookrunners,"Griffin","BMO",.)	
	replace bookrunners = subinstr(bookrunners,"Harris BMO","BMO",.)	
	replace bookrunners = subinstr(bookrunners,"Hapoalim Bm","Hapoalim",.)	
	replace bookrunners = subinstr(bookrunners,"Harrn","Harris Nesbitt",.)	
	replace bookrunners = subinstr(bookrunners,"Hsbc Nada","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Hsbc Pantelakis","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Hsbcap","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Hsbca","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Hsbcs","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Hsbcuk","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Hsbcusa","HSBC",.)
	replace bookrunners = subinstr(bookrunners,"Huntington ","Huntington",.)	
	replace bookrunners = subinstr(bookrunners,"Huntingtons","Huntington",.)	
	replace bookrunners = subinstr(bookrunners,"JP Morgan M","JP Morgan",.)	
	replace bookrunners = subinstr(bookrunners,"JP Morgan Nada","JP Morgan",.)	
	replace bookrunners = subinstr(bookrunners,"Keybk","Keybanc",.)	
	replace bookrunners = subinstr(bookrunners,"Keycorp","Keybanc",.)	
	replace bookrunners = subinstr(bookrunners,"La Slle","La Salle",.)	
	replace bookrunners = subinstr(bookrunners,"Lasalle","La Salle",.)		
	replace bookrunners = subinstr(bookrunners,"Legg Mason Muni","Legg Mason",.)		
	replace bookrunners = subinstr(bookrunners,"Legg Mason Ww","Legg Mason",.)		
	replace bookrunners = subinstr(bookrunners,"Lehman Brothers Eur","Lehman Brothers",.)		
	replace bookrunners = subinstr(bookrunners,"Marshalllsley","Marshall",.)		
	replace bookrunners = subinstr(bookrunners,"Marshall Ller","Marshall",.)		
	replace bookrunners = subinstr(bookrunners,"Mellon","Mellons",.)		
	replace bookrunners = subinstr(bookrunners,"Merrill Lynch Gov","Merrill Lynch",.)		
	replace bookrunners = subinstr(bookrunners,"Mesirow Hldgs","Mesirow",.)		
	replace bookrunners = subinstr(bookrunners,"Mit Tokyo","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mit Ufja","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mit Ufj","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mita","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mitsubishi Ufj","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mizuhon","Mizuho",.)		
	replace bookrunners = subinstr(bookrunners,"Morgan Stanley Japan","Morgan Stanley",.)		
	replace bookrunners = subinstr(bookrunners,"Morgan Stanleybank","Morgan Stanley",.)		
	replace bookrunners = subinstr(bookrunners,"Morgan Stanleyfin","Morgan Stanley",.)		
	replace bookrunners = subinstr(bookrunners,"Mufg Amer","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mufg Enea","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Mufg","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Nat Amer","Natixis",.)		
	replace bookrunners = subinstr(bookrunners,"Natcityest","Natcity",.)		
	replace bookrunners = subinstr(bookrunners,"Nommura Holding","Nommura",.)		
	replace bookrunners = subinstr(bookrunners,"Nommura Am","Nommura Holding",.)		
	replace bookrunners = subinstr(bookrunners,"Nommurai","Nommura",.)		
	replace bookrunners = subinstr(bookrunners,"None","NA",.)		
	replace bookrunners = subinstr(bookrunners,"Piper Jaffray","Piper",.)		
	replace bookrunners = subinstr(bookrunners,"Piper Sandler","NA",.)		
	replace bookrunners = subinstr(bookrunners,"Pnc Nj","PNC",.)		
	replace bookrunners = subinstr(bookrunners,"Pnc Oh","PNC",.)		
	replace bookrunners = subinstr(bookrunners,"Pnc","PNC",.)		
	replace bookrunners = subinstr(bookrunners,"Prude","Prudential",.)		
	replace bookrunners = subinstr(bookrunners,"RBCm","RBC",.)		
	replace bookrunners = subinstr(bookrunners,"Rbs Japan","RBS",.)		
	replace bookrunners = subinstr(bookrunners,"Rbs","RBS",.)		
	replace bookrunners = subinstr(bookrunners,"Salomon Smith Bank of Americarney","Salomon Smith Barney",.)		
	replace bookrunners = subinstr(bookrunners,"Sandler","Sandler O'Neill",.)
	replace bookrunners = subinstr(bookrunners,"Sandler O'Neill O'Neill","Sandler O'Neill",.)		
	replace bookrunners = subinstr(bookrunners,"Scotiaa","Scotia",.)		
	replace bookrunners = subinstr(bookrunners,"Scotiabank","Scotia",.)		
	replace bookrunners = subinstr(bookrunners,"Scotiaa","Scotia",.)		
	replace bookrunners = subinstr(bookrunners,"Scotiaa","Scotia",.)		
	replace bookrunners = subinstr(bookrunners,"Siebert Brand","Siebert",.)		
	replace bookrunners = subinstr(bookrunners,"Siebert Cis","Siebert",.)		
	replace bookrunners = subinstr(bookrunners,"Siebert Will","Siebert",.)		
	replace bookrunners = subinstr(bookrunners,"Simmons Fnb","Simmons",.)		
	replace bookrunners = subinstr(bookrunners,"Simmons F","Simmons",.)		
	replace bookrunners = subinstr(bookrunners,"Socgen","Societe Generale",.)		
	replace bookrunners = subinstr(bookrunners,"Stifel Mo","Stifel",.)		
	replace bookrunners = subinstr(bookrunners,"Suntrust Ami","Suntrust",.)		
	replace bookrunners = subinstr(bookrunners,"Suntrust Equi","Suntrust",.)		
	replace bookrunners = subinstr(bookrunners,"Suntrustcm","Suntrust",.)		
	replace bookrunners = subinstr(bookrunners,"Tda","TD",.)		
	replace bookrunners = subinstr(bookrunners,"UBS ","UBS",.)		
	replace bookrunners = subinstr(bookrunners,"UBS Limited","UBS",.)		
	replace bookrunners = subinstr(bookrunners,"UBSec","UBS",.)		
	replace bookrunners = subinstr(bookrunners,"Ufj","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Usbanc","Us Bancorp",.)		
	replace bookrunners = subinstr(bookrunners,"Wamu","Washington Mutual",.)		
	replace bookrunners = subinstr(bookrunners,"Wash Mutual","Washington Mutual",.)		
	replace bookrunners = subinstr(bookrunners,"Wells Brokerage","Wells Fargo",.)		
	replace bookrunners = subinstr(bookrunners,"Wells Fargo ","Wells Fargo",.)		
	replace bookrunners = subinstr(bookrunners,"Wells Fargoo","Wells Fargo",.)		
	replace bookrunners = subinstr(bookrunners,"Wells Nelson","Wells Fargo",.)		
	replace bookrunners = subinstr(bookrunners,"Zionbcorp","Zions",.)		
	replace bookrunners = subinstr(bookrunners,"Zions Direct","Zions",.)		
	replace bookrunners = subinstr(bookrunners,"Zions Fnb","Zions",.)		
	replace bookrunners = subinstr(bookrunners,"Zions Pub","Zions",.)		
	replace bookrunners = subinstr(bookrunners,"Zionss","Zions",.)		
	replace bookrunners = subinstr(bookrunners,"ABN AMROGov","ABN AMRO",.)		
	replace bookrunners = subinstr(bookrunners,"Bank Montreal","BMO",.)		
	replace bookrunners = subinstr(bookrunners,"Dbj","Deutsche Bank",.)		
	replace bookrunners = subinstr(bookrunners,"Db ","Deutsche Bank",.)		
	replace bookrunners = subinstr(bookrunners,"Dain Rauscher","RBC",.)		
	replace bookrunners = subinstr(bookrunners,"Bank of Americarg","Bank of America",.)		
	replace bookrunners = subinstr(bookrunners,"JP Morgan La","JP Morgan",.)		
	replace bookrunners = subinstr(bookrunners,"Wells Fargo ","Wells Fargo",.)		
	replace bookrunners = subinstr(bookrunners,"Smbc Friend","SMBC",.)		
	replace bookrunners = subinstr(bookrunners,"Smbc Nikko","SMBC",.)		
	replace bookrunners = subinstr(bookrunners,"Smbc ","SMBC",.)		
	replace bookrunners = subinstr(bookrunners,"Smbc","SMBC",.)		
	replace bookrunners = subinstr(bookrunners,"Scotia ","Scotia",.)		
	replace bookrunners = subinstr(bookrunners,"JP Morgan La","JP Morgan",.)		
	replace bookrunners = subinstr(bookrunners,"Hsbc Da","HSBC",.)		
	replace bookrunners = subinstr(bookrunners,"Hsbc ","HSBC",.)		
	replace bookrunners = subinstr(bookrunners,"Hong Shangg","HSBC",.)		
	replace bookrunners = subinstr(bookrunners,"Credit Lyonnaiso","Credit Lyonnais",.)		
	replace bookrunners = subinstr(bookrunners,"Credit Lyonnaiswert","Credit Lyonnais",.)		
	replace bookrunners = subinstr(bookrunners,"Credit Suisse Gibraltar","Credit Suisse",.)		
	replace bookrunners = subinstr(bookrunners,"Credit Suisse Yman","Credit Suisse",.)		
	replace bookrunners = subinstr(bookrunners,"Credri Suis","Credit Suisse",.)		
	replace bookrunners = subinstr(bookrunners,"Citi Glo Hldg","Citi",.)		
	replace bookrunners = subinstr(bookrunners,"Citi ","Citi",.)		
	replace bookrunners = subinstr(bookrunners,"Breanmur Rret","Brean",.)		
	replace bookrunners = subinstr(bookrunners,"Bbva","BBVA",.)		

	*Needs to be at the end
	*These need to be done carefully so they don't change letters unless they are
	*exactly this at the end of the string
	local replace_list `" "Wells" "Hs" "Lloyd" "Deutsche " "Deutsche" "Comm" "Wells" "Multi" "Mit " "Mb" "Hsbc" "Hapo" "Gugg" "Fleet" "Db" "Cs" "Commerz" "Com" "Barclay" "Ak" "Shaw" "Macq" "Raymond" "Raymond " "Macq" "Bnp" "Gs" "Cla" "Cohen" "First Al" "Dominion" "Laz" "Sco" "Soundv" "Td" "Ba" "Barc" "Deutsche" "'
	local new_list `" "Wells Fargo" "HSBC" "Lloyds" "Deutsche Bank" "Deutsche Bank" "Commonwealth Securities" "Wells Fargo" "Multi-Bank Securities" "MUFG" "Multi-Bank Securities" "HSBC" "Hapoalim" "Guggenheim" "Fleet Boston" "Deutsche Bank" "Credit Suisse" "Commerzbank" "Barclays" "AK Capital" "Shaws" "Macquarie" "Raymond James" "Raymond James" "Macquarie" "BNP Paribas" "Goldman Sachs" "Credit Lyonnais" "Cohen and Co." "First Albany" "RBC" "Lazard" "SCO" "Soundview" "TD" "Bank of America" "Barclays" "Deutsche Bank" "'
		
	local n: word count `replace_list'
	forvalues i = 1/`n' {
		local a: word `i' of `replace_list'
		local b: word `i' of `new_list'
		replace bookrunners = subinstr(bookrunners,"`a'","`b'",.) ///
			if regexm(bookrunners,"`a'/") | regexm(bookrunners,"`a'$")
	}

	replace bookrunners = subinstr(bookrunners,"Bank Of America","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of America Ca","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americaap","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americaa","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americav","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americacm","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americacs","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americank of America","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americankone","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bnpparibas Asia","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"First RBC","First Dominion",.)
	replace bookrunners = subinstr(bookrunners,"RBCinion","First Dominion",.)
	replace bookrunners = subinstr(bookrunners,"Dbsecu","Deutsche Bank",.)
	replace bookrunners = subinstr(bookrunners,"Piperaffray","Piper Jaffray",.)
	replace bookrunners = subinstr(bookrunners,"Americaowth","AGC",.)
	replace bookrunners = subinstr(bookrunners,"Morgan Stanley Nada","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Mac Eq Cm","Macquarie",.)
	replace bookrunners = subinstr(bookrunners,"Macquariea","Macquarie",.)
	replace bookrunners = subinstr(bookrunners,"Morgan StanleyMorgan Stanley","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Credita","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Barccg","Barclays",.)
	replace bookrunners = subinstr(bookrunners,"Cantor Fitz","Cantor",.)
	replace bookrunners = subinstr(bookrunners,"Raymond James James","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Barclaysnk One","Bank One",.)		
	replace bookrunners = subinstr(bookrunners,"Barclaysnk of America","Bank of America",.)		
	replace bookrunners = subinstr(bookrunners,"Barclaysnk of America","Barclays",.)		
	replace bookrunners = subinstr(bookrunners,"Credit Lyonnais Es","Credit Lyonnais",.)		
	replace bookrunners = subinstr(bookrunners,"Credit Suissepe","Credit Suisse",.)				
	replace bookrunners = subinstr(bookrunners,"Deutsche Barclaysnk","Deutsche Bank",.)		
	replace bookrunners = subinstr(bookrunners,"First Tenn ","First Tenn",.)		 
	replace bookrunners = subinstr(bookrunners,"Fleet Boston Boston","Fleet Boston",.)		 
	replace bookrunners = subinstr(bookrunners,"Fleet BostonBoston","Fleet Boston",.)		 
	replace bookrunners = subinstr(bookrunners,"GMAC RFCercial","GMAC RFC",.)		 
	replace bookrunners = subinstr(bookrunners,"JP Morgan Da","JP Morgan",.)		 
	replace bookrunners = subinstr(bookrunners,"JP Morgan La","JP Morgan",.)		 
	replace bookrunners = subinstr(bookrunners,"Jefferiesp L","Jefferies",.)		 
	replace bookrunners = subinstr(bookrunners,"La Salle ","La Salle",.)	
	replace bookrunners = subinstr(bookrunners,"MUFG Emea","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Morgan Stanley MUFG","Morgan Stanley",.)		
	replace bookrunners = subinstr(bookrunners,"Nommura","Nomura",.)		
	replace bookrunners = subinstr(bookrunners,"Nomurai","Nomura",.)		
	replace bookrunners = subinstr(bookrunners,"Nommura Am","Nomura",.)		
	replace bookrunners = subinstr(bookrunners,"Piper Jaffray","Piper",.)		
	replace bookrunners = subinstr(bookrunners,"Prudentialntial","Prudential",.)		
	replace bookrunners = subinstr(bookrunners,"RBC ","RBC",.)		
	replace bookrunners = subinstr(bookrunners,"UBSLimited","UBS",.)		
	replace bookrunners = subinstr(bookrunners,"Us Barclaysncorp","US Bancorp",.)		
	replace bookrunners = subinstr(bookrunners,"Us Bancorp","US Bancorp",.)		  	
	replace bookrunners = subinstr(bookrunners,"Us Bancorp","Mellons",.)		  	
	replace bookrunners = subinstr(bookrunners,"JP Morgan La","JP Morgan",.)		
	replace bookrunners = subinstr(bookrunners,"US Barclaysncorp","US Bancorp",.)		
	replace bookrunners = subinstr(bookrunners,"UBSSz","UBS",.)		
	replace bookrunners = subinstr(bookrunners,"UBSsng","UBS",.)		
	replace bookrunners = subinstr(bookrunners,"US Bancorporp  Pa","US Bancorp",.)		
	replace bookrunners = subinstr(bookrunners,"Td Amer","TD",.)		
	replace bookrunners = subinstr(bookrunners,"Tdbank","TD",.)		
	replace bookrunners = subinstr(bookrunners,"Stand ","Stand",.)		
	replace bookrunners = subinstr(bookrunners,"Salomon Smith Barclaysrney","Salomon Smith Barney",.)		
	replace bookrunners = subinstr(bookrunners,"RBCe","RBC",.)		
	replace bookrunners = subinstr(bookrunners,"RBSp","RBS",.)		
	replace bookrunners = subinstr(bookrunners,"PNC ","PNC",.)		
	replace bookrunners = subinstr(bookrunners,"Morgan Stanley Da","Morgan Stanley",.)		
	replace bookrunners = subinstr(bookrunners,"Mellonss ","Mellons",.)		
	replace bookrunners = subinstr(bookrunners,"Macquarieur","Macquarie",.)		
	replace bookrunners = subinstr(bookrunners,"Macquarie Credit Suisse","Macquarie",.)		
	replace bookrunners = subinstr(bookrunners,"Macquarie ","Macquarie",.)		
	replace bookrunners = subinstr(bookrunners,"MUFG Union","MUFG",.)		
	replace bookrunners = subinstr(bookrunners,"Macquarieur","Macquarie",.)		
	replace bookrunners = subinstr(bookrunners,"Deutsche Banklays","Deutsche Bank",.)		
	replace bookrunners = subinstr(bookrunners,"Deutsche N","Deutsche Bank",.)		
	replace bookrunners = subinstr(bookrunners,"Barclaysrclays","Barclays",.)		
	replace bookrunners = subinstr(bookrunners,"BONY Ss","BONY",.)		
	replace bookrunners = subinstr(bookrunners,"Wells FargoMn","Wells Fargo",.)		
	replace bookrunners = subinstr(bookrunners,"Wells Fargo ","Wells Fargo",.)		

	
	*Converting acquisitions
	replace bookrunners = subinstr(bookrunners,"Bank One","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Bear Stearns","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Merrill Lynch","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Wachovia","Wells Fargo",.)
	replace bookrunners = subinstr(bookrunners,"Salomon Smith Barney","Citi",.)

end


*For the second round, copying from Ben's code
cap program drop clean_lender_sdc
program define clean_lender_sdc
replace lender = "1st Farm Credit" if regexm(lender,"1st Farm Credit")
replace lender = "ABN AMRO" if regexm(lender,"ABN AMRO")
replace lender = "ABB" if regexm(lender,"ABB ")
replace lender = "ABC" if regexm(lender,"ABC ")
replace lender = "ABSA" if regexm(lender,"ABSA ")
replace lender = "ACA" if substr(lender,1,4)=="ACA "
replace lender = "ACE" if substr(lender,1,4)=="ACE "
replace lender = "ACL" if substr(lender,1,4)=="ACL "
replace lender = "AG" if substr(lender,1,3)=="AG "
replace lender = "AIB" if substr(lender,1,4)=="AIB "
replace lender = "AIG" if substr(lender,1,4)=="AIG " | substr(lender,1,4)=="AIG-"
replace lender = "AMMC" if substr(lender,1,4)=="AMMC"
replace lender = "AMP" if substr(lender,1,4)=="AMP "
replace lender = "ANZ" if substr(lender,1,4)=="ANZ "
replace lender = "APEX" if substr(lender,1,5)=="APEX "
replace lender = "AS" if substr(lender,1,3)=="AS "
replace lender = "ASB" if substr(lender,1,4)=="ASB "
replace lender = "AXA" if substr(lender,1,4)=="AXA "
replace lender = "AZB" if substr(lender,1,4)=="AZB "
replace lender = "Abanca" if regexm(lender,"Abanca")
replace lender = "Ableco" if regexm(lender,"Ableco")
replace lender = "Aeon" if regexm(lender,"Aeon")
replace lender = "Affin" if substr(lender,1,6)=="Affin "
replace lender = "Agricultural Bank of China" if regexm(lender,"Agricultural Bank of China")
replace lender = "Ahli" if substr(lender,1,5)=="Ahli "
replace lender = "Aichi" if substr(lender,1,6)=="Aichi "
replace lender = "Aimco" if regexm(lender,"Aimco")
replace lender = "Airbus" if regexm(lender,"Airbus")
replace lender = "Airlie" if regexm(lender,"Airlie")
replace lender = "Akita" if regexm(lender,"Akita")
replace lender = "Alcatel-Lucent" if regexm(lender,"Alcatel-Lucent")
replace lender = "Alcentra" if regexm(lender,"Alcentra")
replace lender = "Alfa Bank" if regexm(lender,"Alfa Bank")
replace lender = "Allen & Overy" if regexm(lender,"Allen & Overy")
replace lender = "Alliance & Leicester" if regexm(lender,"Alliance & Leicester")
replace lender = "Alliance Bank" if regexm(lender,"Alliance Bank")
replace lender = "Allianz" if regexm(lender,"Allianz")
replace lender = "Allstate" if regexm(lender,"Allstate")
replace lender = "Ally" if substr(lender,1,5)=="Ally "
replace lender = "Alostar" if regexm(lender,"Alostar")
replace lender = "Alpha Bank" if regexm(lender,"Alpha Bank")
replace lender = "AmSouth" if regexm(lender,"AmSouth")
replace lender = "American Bank" if regexm(lender,"American Bank")
replace lender = "American Express" if regexm(lender,"American Express")
replace lender = "AIG" if regexm(lender,"American International Group")
replace lender = "American National Bank" if regexm(lender,"American National Bank")
replace lender = "Anhui" if regexm(lender,"Anhui")
replace lender = "Apollo" if regexm(lender,"Apollo")
replace lender = "Arab Bank" if regexm(lender,"Arab Bank")
replace lender = "Ares" if substr(lender,1,5) == "Ares "
replace lender = "Atrium" if regexm(lender,"Atrium")
replace lender = "Audax" if regexm(lender,"Audax")
replace lender = "Australia & New Zealand Banking Group" if regexm(lender,"Australia & New Zealand")
replace lender = "Aviva" if regexm(lender,"Aviva")
replace lender = "Axis Bank" if regexm(lender,"Axis Bank")
replace lender = "BBVA" if regexm(lender,"BBVA")
replace lender = "BNP Paribas" if regexm(lender,"BNP Paribas")
replace lender = "BMCE Bank" if regexm(lender,"BMCE Bank")
replace lender = "BMO" if substr(lender,1,4)=="BMO "
replace lender = "BPD" if substr(lender,1,4)=="BPD "
replace lender = "RBC" if substr(lender,1,4)=="RBC "
replace lender = "TD " if substr(lender,1,3)=="TD "
replace lender = "UBS" if substr(lender,1,4)=="UBS "
replace lender = "UFJ" if substr(lender,1,4)=="UFJ "
replace lender = "CIBC" if substr(lender,1,5)=="CIBC "
replace lender = "DBS" if substr(lender,1,4)=="DBS "
replace lender = "ING" if substr(lender,1,4)=="ING "
replace lender = "RBS" if substr(lender,1,4)=="RBS "
replace lender = "GSO" if substr(lender,1,4)=="GSO "
replace lender = "IBJ" if substr(lender,1,4)=="IBJ "
replace lender = "HSH" if substr(lender,1,4)=="HSH "
replace lender = "OCM" if substr(lender,1,4)=="OCM "
replace lender = "RHB" if substr(lender,1,4)=="RHB "
replace lender = "ICBC" if substr(lender,1,5)=="ICBC "
replace lender = "ICICI" if substr(lender,1,6)=="ICICI "
replace lender = "Fidelity" if substr(lender,1,9)=="Fidelity "
replace lender = "Fortress" if substr(lender,1,9)=="Fortress "


replace lender = "CIT" if substr(lender,1,4)=="CIT "
replace lender = "KZH" if substr(lender,1,3)=="KZH"
replace lender = "PNC" if substr(lender,1,4)=="PNC "

replace lender = "Banca Popolare" if regexm(lender, "Banca Popolare")
replace lender = "Bank One" if regexm(lender, "Bank One")
replace lender = "Bank of Tokyo" if regexm(lender, "Bank of Tokyo")
replace lender = "Barclays" if regexm(lender,"Barclays")
replace lender = "Black Diamond" if regexm(lender, "Black Diamond")
replace lender = "BlackRock" if regexm(lender, "Blackrock") | regexm(lender,"BlackRock") | ///
								regexm(lender,"Black rock") | regexm(lender,"Black Rock")
replace lender = "Carlyle" if regexm(lender, "Carlyle") 
replace lender = "Caspian" if regexm(lender, "Caspian")
replace lender = "Citibank" if regexm(lender, "Citibank")
replace lender = "Citigroup" if regexm(lender, "Citigroup")
replace lender = "Commerzbank" if regexm(lender, "Commerzbank") | regexm(lender, "Comerzbank")
replace lender = "Chase Manhattan" if regexm(lender, "Chase Manhattan")
replace lender = "Chang Hwa Commerican Bank" if regexm(lender, "Chan") & regexm(lender,"wa")
replace lender = "China Construction Bank" if regexm(lender, "China Construction Bank")
replace lender = "Citizens Bank" if regexm(lender, "Citizens Bank")
replace lender = "Credit Agricole" if regexm(lender, "Credit Agricole")
replace lender = "Credit Industriel et Commercial" if regexm(lender, "Credit Industriel")
replace lender = "Credit Lyonnais" if regexm(lender, "Credit Lyonnais")
replace lender = "Credit Suisse" if regexm(lender, "Credit Suisse")
replace lender = "CypressTree" if regexm(lender, "Cypress") & regexm(lender,"ree")
replace lender = "Eaton Vance" if regexm(lender, "Eaton Vance") | regexm(lender,"Eatonvance")
replace lender = "Farm Credit" if regexm(lender, "Farm Credit")
replace lender = "First Commercial Bank" if regexm(lender, "First Commercial")
replace lender = "First Union" if regexm(lender, "First Union")
replace lender = "First National Bank" if regexm(lender, "First National Bank")
replace lender = "Fortis" if regexm(lender, "Fortis")
replace lender = "GE" if substr(lender,1,3) == "GE "
replace lender = "General Electric" if regexm(lender, "General Electric")
replace lender = "GoldenTree" if regexm(lender, "Golden") & (regexm(lender,"tree") | regexm(lender,"Tree"))
replace lender = "Golub Capital" if regexm(lender, "Golub Capital")
replace lender = "Goldman Sachs" if regexm(lender,"Goldman Sachs")
replace lender = "Guggenheim" if regexm(lender,"Guggenheim")
replace lender = "Highland" if regexm(lender,"Highland")
replace lender = "Highbridge" if regexm(lender,"Highbridge")
replace lender = "HSBC" if regexm(lender, "HSBC")
replace lender = "Hua Nan Commercial Bank" if regexm(lender, "Hua Nan Commercial Bank")
replace lender = "Industrial & Commercial Bank of China" if regexm(lender,"Industrial & Commercial Bank of China")
replace lender = "Intesa Sanpaolo" if regexm(lender,"Intesa")
replace lender = "Jefferies" if regexm(lender,"Jefferies")
replace lender = "JP Morgan" if regexm(lender, "JP Morgan") | regexm(lender,"JPM")
replace lender = "KKR" if regexm(lender, "KKR")
replace lender = "Lehman" if regexm(lender, "Lehman")
replace lender = "John Hancock" if regexm(lender, "John Hancock")
replace lender = "Lloyds" if regexm(lender, "Lloyds")
replace lender = "Mass Mutual" if regexm(lender, "Mass") & regexm(lender,"utual")
replace lender = "Macquarie" if regexm(lender, "Macquarie")
replace lender = "Maybank" if regexm(lender, "Maybank")
replace lender = "Mega International Commercial Bank" if regexm(lender,"Mega International")
replace lender = "Merrill Lynch" if regexm(lender,"Merrill Lynch")
replace lender = "Monroe Capital" if regexm(lender,"Monroe Capital")
replace lender = "Morgan Stanley" if regexm(lender,"Morgan Stanley")
replace lender = "MetLife" if regexm(lender,"Metlife") | regexm(lender,"MetLife") ///
				| (regexm(lender,"Metropolitan") & regexm(lender,"ife"))
				
replace lender = "Mitsubishi" if regexm(lender,"Mitsubishi")
replace lender = "Mizuho" if regexm(lender,"Mizuho")
replace lender = "Nomura" if regexm(lender,"Nomura")
replace lender = "Oak Hill" if regexm(lender,"Oak Hill")
replace lender = "PIMCO" if regexm(lender,"PIMCO") | regexm(lender,"Pimco")
replace lender = "Pilgrim" if substr(lender,1,8) == "Pilgrim "
replace lender = "Provident" if regexm(lender,"Provident ")
replace lender = "Prudential" if regexm(lender,"Prudential")
replace lender = "Putnam" if regexm(lender,"Putnam")
replace lender = "PT Bank" if regexm(lender,"PT Bank")
replace lender = "Rabobank" if regexm(lender,"Rabobank")
replace lender = "Raymond James" if regexm(lender,"Raymond James")
replace lender = "Santander" if regexm(lender,"Santander")
replace lender = "Scotiabank" if regexm(lender,"Scotiabank")
replace lender = "Societe Generale" if regexm(lender,"Societe Generale")
replace lender = "State Bank of India" if regexm(lender,"State Bank of India")
replace lender = "Sumitomo Mitsui" if regexm(lender,"Sumitomo Mitsui")
replace lender = "SunTrust" if regexm(lender,"SunTrust") | regexm(lender,"Suntrust")
replace lender = "Transamerica" if regexm(lender,"Transamerica") | regexm(lender,"TransAmerica")
replace lender = "UniCredit" if regexm(lender,"UniCredit")
replace lender = "Union Bank" if regexm(lender,"Union Bank")
replace lender = "Wachovia" if regexm(lender,"Wachovia")
replace lender = "Washington Mutual" if regexm(lender,"Washington Mutual")
replace lender = "Wells Fargo" if regexm(lender,"Wells Fargo")
replace lender = "Wells Fargo" if regexm(lender,"Wells") 
replace lender = "Toronto Dom" if regexm(lender,"TD") 


foreach i in "Bank of America" "Charles Schwab" "Royal Bank of Canada" "Royal Bank of Scotland" "SBI" "SMBC" ///
	"Sankaty" "Salomon Smith Barney" "Scottrade" "Shanghai Commercial" ///
	"Southwest Bank" "Standard Chartered Bank" "Stanfield" "Svenska Handelsbanken" ///
	"TIAA" "Taipei Fubon Commercial Bank" "Tennenbaum" "Toronto Dominion" "Travelers" ///
	"Van Kampen" "Whippoorwill" "Whitehall" "William Street" "Bayerische Landesbank" ///
	"Bear Stearns" "Capital One" "Captiva" "Citicorp" "City National Bank" "Clydesdale" ///
	"Comerica Bank" "DE Shaw" "Daiwa Securities" "Denali" "Dryden" "Farallon"  ///
	"Foothill" "Franklin" "Gallatin" "General Motors" "Gulf Stream" "Indosuez Capital" ///
	"International Commercial Bank of China" "Laurentian" "Lazard" "Liberty Mutual" ///
	"LightPoint" "MUFG" "Magnetite" "Mainstay" "Malayan Banking" "Mellon Bank" ///
	"NatWest" "National Australia Bank" "National City Bank" "National Westminster Bank" ///
	"Nationwide" "Nedbank" "Nordea Bank" "Northern Trust" "Nuveen" "Oaktree" "Bain Capital" ///
	{
		
		replace lender = "`i'" if regexm(lender,"`i'")
	
	}
	
replace lender = "JP Morgan" if lender == "Chase"
replace lender = "Wells Fargo" if lender == "WF"
	
	
end

cap program drop sdc_wide_to_long
program define sdc_wide_to_long

	keep bookrunner_* sdc_deal_id cusip_6
	reshape long bookrunner_, i(sdc_deal_id) j(num)
	*Rename this to the same variable as the dealscan lender variable
	rename bookrunner_ lender
	drop if mi(lender)
	drop num
	replace lender = trim(lender)
	drop if lender == "NA" | lender== "TBD" | lender == "Unknown"
	clean_lender_sdc
	replace lender = upper(lender)
	duplicates drop




end
