*Will turn these into functions that will standardize names
cap program drop standardize_bookrunners
program define standardize_bookrunners
	replace bookrunners = subinstr(bookrunners,",","",.)
	replace bookrunners = subinstr(bookrunners,"(JB)","",.)
	*Remove some common suffixes, then eventually turn to lowercase
	replace bookrunners = subinstr(bookrunners,"-CAPITAL","",.)
	replace bookrunners = subinstr(bookrunners,"-CAP","",.)
	replace bookrunners = subinstr(bookrunners,"-GROUP","",.)
	replace bookrunners = subinstr(bookrunners,"-PLC","",.)
	replace bookrunners = subinstr(bookrunners,"-SECURITIES","",.)
	replace bookrunners = subinstr(bookrunners,"-SEC","",.)
	replace bookrunners = subinstr(bookrunners,"-UK","",.)
	replace bookrunners = subinstr(bookrunners,"-GR","",.)
	replace bookrunners = subinstr(bookrunners,"-EURO","",.)
	replace bookrunners = subinstr(bookrunners,"-PARTNER","",.)
	replace bookrunners = subinstr(bookrunners,"-PTNRS","",.)
	replace bookrunners = subinstr(bookrunners,"-LLC","",.)
	replace bookrunners = subinstr(bookrunners,"-LTD","",.)
	replace bookrunners = subinstr(bookrunners,"-FINANCIAL","",.)
	replace bookrunners = subinstr(bookrunners,"-FIN","",.)
	replace bookrunners = subinstr(bookrunners,"-CORP","",.)
	replace bookrunners = subinstr(bookrunners,"-CO","",.)
	replace bookrunners = subinstr(bookrunners,"-INC","",.)
	replace bookrunners = subinstr(bookrunners,"-INV","",.)
	replace bookrunners = subinstr(bookrunners,"-US","",.)
	replace bookrunners = subinstr(bookrunners,"-AG","",.)
	replace bookrunners = subinstr(bookrunners,"-AUS","",.)
	replace bookrunners = subinstr(bookrunners,"-INTL","",.)
	replace bookrunners = subinstr(bookrunners,"-INT","",.)
	replace bookrunners = subinstr(bookrunners,"-HK","",.)
	replace bookrunners = subinstr(bookrunners,"-AU","",.)
	replace bookrunners = subinstr(bookrunners,"-MKT","",.)
	replace bookrunners = subinstr(bookrunners,"-GRP","",.)
	replace bookrunners = subinstr(bookrunners,"-BANK","",.)
	replace bookrunners = subinstr(bookrunners,"-BNK","",.)
	replace bookrunners = subinstr(bookrunners,"-BK","",.)
	replace bookrunners = subinstr(bookrunners,"-GRP","",.)
	replace bookrunners = subinstr(bookrunners,"-LP","",.)
	replace bookrunners = subinstr(bookrunners,"-MARKETS","",.)
	replace bookrunners = subinstr(bookrunners,"-NY","",.)
	replace bookrunners = subinstr(bookrunners,"-HQ","",.)
	replace bookrunners = subinstr(bookrunners,"-I","",.)
	replace bookrunners = subinstr(bookrunners,"-"," ",.)
	replace bookrunners = subinstr(bookrunners,"_"," ",.)
	replace bookrunners = subinstr(bookrunners," GIBRALTOR"," ",.)
	replace bookrunners = subinstr(bookrunners," CA"," ",.)	
	replace bookrunners = subinstr(bookrunners," PVT"," ",.)
	replace bookrunners = subinstr(bookrunners," LLP"," ",.)
	replace bookrunners = subinstr(bookrunners," ASIA"," ",.)
	replace bookrunners = subinstr(bookrunners," VK"," ",.)

	
	*Now make them proper case
	replace bookrunners = proper(bookrunners)
	*Now standardize them
	replace bookrunners = subinstr(bookrunners,"Dlj","Donaldson Lufkin & Jenrette",.)
	replace bookrunners = subinstr(bookrunners,"Salomon Smith","Salomon Smith Barney",.)
	replace bookrunners = subinstr(bookrunners,"Merrill","Merrill Lynch",.)
	replace bookrunners = subinstr(bookrunners,"Cs Fb Cs","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Cs Fb","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Deutsche Alex B","Deutsche Bank",.)
	replace bookrunners = subinstr(bookrunners,"Csfb","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Cibc World","CIBC",.)
	replace bookrunners = subinstr(bookrunners,"Leh","Lehman Brothers",.)
	replace bookrunners = subinstr(bookrunners,"Jpmch","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jpmp","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jpml","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jpm","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Ml","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Msdw","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Bear","Bear Stearns",.)
	replace bookrunners = subinstr(bookrunners,"Psi","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"Cowen","Societe Generale",.)
	replace bookrunners = subinstr(bookrunners,"Friedman B","FBR",.)
	replace bookrunners = subinstr(bookrunners,"Hambrecht","Hambrecht & Quist",.)
	replace bookrunners = subinstr(bookrunners,"Ing Barings","ING",.)
	replace bookrunners = subinstr(bookrunners,"Warburg Dr","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Wdr","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Sutro","Sutro & Co",.)
	replace bookrunners = subinstr(bookrunners,"Us Piper","US Bancorp",.)
	replace bookrunners = subinstr(bookrunners,"Ubs Warburg","UBS",.)
	replace bookrunners = subinstr(bookrunners,"A G Edwards","A.G. Edwards",.)
	replace bookrunners = subinstr(bookrunners,"Adams Harkness","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Brous","HD Brous",.)
	replace bookrunners = subinstr(bookrunners,"Boston Roberts","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Gunnar","Joseph Gunnar",.)
	replace bookrunners = subinstr(bookrunners,"C S F B","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Kashner","Kashner Davidson",.)
	replace bookrunners = subinstr(bookrunners,"Fleet Rob Steph","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Prud Volpe","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"Pru Vec Hc","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"To Be Announced","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Mcdonald","McDonald",.)
	replace bookrunners = subinstr(bookrunners,"Robertson S","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Neidiger","NTB Financial",.)
	replace bookrunners = subinstr(bookrunners,"Wit Soundview","Charles Schwab",.)
	replace bookrunners = subinstr(bookrunners,"Inst Equity","Institutional Equity",.)
	replace bookrunners = subinstr(bookrunners,"H C Wainwright","HC Wainwright",.)
	replace bookrunners = subinstr(bookrunners,"Paulson","Paulson Investment",.)
	replace bookrunners = subinstr(bookrunners,"Warburg","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Paine W","Paine Webber",.)
	replace bookrunners = subinstr(bookrunners,"Penn Mer","PMG Capital",.)
	replace bookrunners = subinstr(bookrunners,"Robinson","Truist",.)
	replace bookrunners = subinstr(bookrunners,"Starr","Starr Securities",.)
	replace bookrunners = subinstr(bookrunners,"Dain R Wessels","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Hwnt","Hornblower & Weeks",.)
	replace bookrunners = subinstr(bookrunners,"Notapp","NA",.)
	replace bookrunners = subinstr(bookrunners,"Fahnestock","Oppenheimer",.)
	replace bookrunners = subinstr(bookrunners,"Burnham","Burnham Securities",.)
	replace bookrunners = subinstr(bookrunners,"Dg","DZ Bank",.)
	replace bookrunners = subinstr(bookrunners,"Fbsi","Fleet Boston",.)
	replace bookrunners = subinstr(bookrunners,"Not Available","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Pru Vec Hc","Prudential",.)
	replace bookrunners = subinstr(bookrunners,"Bb T Cap","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"First Union","Wells Fargo",.)
	replace bookrunners = subinstr(bookrunners,"Csmsc","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Csa","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Deutsche A","Deutsche Bank",.)
	replace bookrunners = subinstr(bookrunners,"Van Kasper","Wells Fargo",.)
	replace bookrunners = subinstr(bookrunners,"Schneider","Schneider Securities",.)
	replace bookrunners = subinstr(bookrunners,"Sandler Oneill","Sandler O'Neill",.)
	replace bookrunners = subinstr(bookrunners,"Coneff","Concord",.)
	replace bookrunners = subinstr(bookrunners,"Morgan Keegan","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Somerset","Somerset Financial",.)
	replace bookrunners = subinstr(bookrunners,"Raymond James Ca","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Calaz","Credit Agricole",.)
	replace bookrunners = subinstr(bookrunners,"Tucker","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Wm Blair","William Blair",.)
	replace bookrunners = subinstr(bookrunners,"Centex","Centex Securities",.)
	replace bookrunners = subinstr(bookrunners,"Unspecified","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Mdb","MDB Capital",.)
	replace bookrunners = subinstr(bookrunners,"Williams","Investec",.)
	replace bookrunners = subinstr(bookrunners,"Whale","Whale Securities",.)
	replace bookrunners = subinstr(bookrunners,"Mercer Part","Mercer",.)
	replace bookrunners = subinstr(bookrunners,"Abn Amro","ABN AMRO",.)
	replace bookrunners = subinstr(bookrunners,"Abn Rothschild","ABN AMRO",.)
	replace bookrunners = subinstr(bookrunners,"Ag Edwards","AG Edwards",.)
	replace bookrunners = subinstr(bookrunners,"A.G. Edwards","AG Edwards",.)
	replace bookrunners = subinstr(bookrunners,"Adsm","Adam Smith Institute",.)
	replace bookrunners = subinstr(bookrunners,"Aps","APS",.)
	replace bookrunners = subinstr(bookrunners,"Atcapi","Atlas",.)
	replace bookrunners = subinstr(bookrunners,"B Riley Fbr","Merrill Lynch",.)
	replace bookrunners = subinstr(bookrunners,"Bathgate Mccoll","Bathgate",.)
	replace bookrunners = subinstr(bookrunners,"Bb T","BB&T",.)
	replace bookrunners = subinstr(bookrunners,"Bk Berlin","Berliner Handels",.)
	replace bookrunners = subinstr(bookrunners,"Bkrs Wi","Bankers Bank of Wisconsin",.)
	replace bookrunners = subinstr(bookrunners,"Bmo Nesbitt","BMO",.)
	replace bookrunners = subinstr(bookrunners,"Bmo Nes","BMO",.)
	replace bookrunners = subinstr(bookrunners,"Bmo","BMO",.)
	replace bookrunners = subinstr(bookrunners,"Bnp Paribas","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"Bnparf","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"Boa Merrill Lynch","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bofa","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Breanmur Carret","Brean",.)
	replace bookrunners = subinstr(bookrunners,"Bsi","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Burnham Securities Hill","Burnham Securities",.)
	replace bookrunners = subinstr(bookrunners,"Btig","BTIG",.)
	replace bookrunners = subinstr(bookrunners,"Can Adams","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Can Fitz","Cantor",.)
	replace bookrunners = subinstr(bookrunners,"Cant Fitz","Cantor",.)
	replace bookrunners = subinstr(bookrunners,"Can Genuity","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Canaccord Gen","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Cdc","CDC",.)
	replace bookrunners = subinstr(bookrunners,"Cgf","CGF",.)
	replace bookrunners = subinstr(bookrunners,"Cibc","CIBC",.)
	replace bookrunners = subinstr(bookrunners,"Citigroup","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citgrp","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citi Gm","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Citi Ssb","Citi",.)
	replace bookrunners = subinstr(bookrunners,"Cs Hk","Credit Suisse",.)
	replace bookrunners = subinstr(bookrunners,"Ckop","CK Cooper",.)
	replace bookrunners = subinstr(bookrunners,"Chinatrustmm","Chinatrust",.)
	replace bookrunners = subinstr(bookrunners,"Clsa HK","CLSA",.)
	replace bookrunners = subinstr(bookrunners,"Clsa Equity","CLSA",.)
	replace bookrunners = subinstr(bookrunners,"Dnb Nor","DNB",.)
	replace bookrunners = subinstr(bookrunners,"Dnb","DNB",.)
	replace bookrunners = subinstr(bookrunners,"Ed Jones","Edward Jones",.)
	replace bookrunners = subinstr(bookrunners,"Ekn","EKN",.)
	replace bookrunners = subinstr(bookrunners,"Empire Asset","Empire",.)
	replace bookrunners = subinstr(bookrunners,"Ev Distributors","Eaton Vance",.)
	replace bookrunners = subinstr(bookrunners,"Fantex B","Fantex",.)
	replace bookrunners = subinstr(bookrunners,"Fbr","FBR",.)
	replace bookrunners = subinstr(bookrunners,"Figs","Fig",.)
	replace bookrunners = subinstr(bookrunners,"First Dun","First Dunbar",.)
	replace bookrunners = subinstr(bookrunners,"Forbes Pcg","Forbes",.)
	replace bookrunners = subinstr(bookrunners,"Ftn Midwest","FTN Midwest",.)
	replace bookrunners = subinstr(bookrunners,"Gbs Ventures","GBS Ventures",.)
	replace bookrunners = subinstr(bookrunners,"Genuity","Canaccord",.)
	replace bookrunners = subinstr(bookrunners,"Gmp","GMP",.)
	replace bookrunners = subinstr(bookrunners,"Great Am Adv","Great American Adventures",.)
	replace bookrunners = subinstr(bookrunners,"Griffin Kubik","Griffin",.)
	replace bookrunners = subinstr(bookrunners,"J P Morgan","JP Morgan",.)
	replace bookrunners = subinstr(bookrunners,"Jf Mackie","JF Mackie",.)
	replace bookrunners = subinstr(bookrunners,"Jmp","JMP",.)
	replace bookrunners = subinstr(bookrunners,"Jp","JP Carey",.)
	replace bookrunners = subinstr(bookrunners,"Kbc_Peel_Hunt","KBC Peel Hunt",.)
	replace bookrunners = subinstr(bookrunners,"Key Banc","Keybanc",.)
	replace bookrunners = subinstr(bookrunners,"Kgi Tw","KGI",.)
	replace bookrunners = subinstr(bookrunners,"Kkr","KKR",.)
	replace bookrunners = subinstr(bookrunners,"Ms","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Macquarie Ca","Macquarie",.)
	replace bookrunners = subinstr(bookrunners,"Mizuhoa","Mizuho",.)
	replace bookrunners = subinstr(bookrunners,"Morgan Stanley Canada","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Natl","National",.)
	replace bookrunners = subinstr(bookrunners,"National City","National",.)
	replace bookrunners = subinstr(bookrunners,"Nd","TBD",.)
	replace bookrunners = subinstr(bookrunners,"Newport C","Newport Coast",.)
	replace bookrunners = subinstr(bookrunners,"Nobleer","Noble",.)
	replace bookrunners = subinstr(bookrunners,"Northland Cp","Northland",.)	
	replace bookrunners = subinstr(bookrunners,"Non Underwritte","NA",.)
	replace bookrunners = subinstr(bookrunners,"Piper Jaffrey","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Piper J","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Piper Muni","Piper",.)
	replace bookrunners = subinstr(bookrunners,"Pmg","PMG",.)
	replace bookrunners = subinstr(bookrunners,"Pryorunts","Pryor Counts",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Cm","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Cs","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Dain","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc Dom","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbcs","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rbc","RBC",.)
	replace bookrunners = subinstr(bookrunners,"Rayjam","Raymond James",.)
	replace bookrunners = subinstr(bookrunners,"Scot String","Scott String",.)
	replace bookrunners = subinstr(bookrunners,"Sgwen","Cowen",.)
	replace bookrunners = subinstr(bookrunners,"Shinhanr","Shinhan",.)
	replace bookrunners = subinstr(bookrunners,"Ssec","Sunrise",.)
	replace bookrunners = subinstr(bookrunners,"Sterneee","Sterne",.)
	replace bookrunners = subinstr(bookrunners,"Suntrust Rh","Suntrust",.)
	replace bookrunners = subinstr(bookrunners,"Svb Leerink","SVB Leerink",.)
	replace bookrunners = subinstr(bookrunners,"Ubs","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Invbnk","Investec",.)

	replace bookrunners = subinstr(bookrunners,"Bacabv","Bank Austria",.)
	replace bookrunners = subinstr(bookrunners,"Bocia","BOCI",.)
	replace bookrunners = subinstr(bookrunners,"Boci","BOCI",.)
	replace bookrunners = subinstr(bookrunners,"Investecest","Investec",.)
	replace bookrunners = subinstr(bookrunners,"Mufj Morgan Stanley","Morgan Stanley",.)
	replace bookrunners = subinstr(bookrunners,"Wedbush M ","Wedbush",.)
	replace bookrunners = subinstr(bookrunners,"UBS Pincus","UBS",.)
	replace bookrunners = subinstr(bookrunners,"UBSau","UBS",.)
	replace bookrunners = subinstr(bookrunners,"UBSb","UBS",.)
	replace bookrunners = subinstr(bookrunners,"UBSec Pincus","UBS",.)
	replace bookrunners = subinstr(bookrunners,"Nationalt","National",.)
	replace bookrunners = subinstr(bookrunners,"Lehman Brothersman","Lehman Brothers",.)
	replace bookrunners = subinstr(bookrunners,"JP Morgan Chase","JP Morgan",.)
	*Needs to be at the end
	*These need to be done carefully so they don't change letters unless they are
	*exactly this at the end of the string
	local replace_list `" "Piper" "Shaw" "Macq" "Raymond" "Raymond " "Macq" "Bnp" "Gs" "Cla" "Cohen" "First Al" "Dominion" "Laz" "Sco" "Soundv" "Td" "Ba" "Barc" "Deutsche" "'
	local new_list `" "Piper Jaffrey" "Shaws" "Macquarie" "Raymond James" "Raymond James" "Macquarie" "BNP Paribas" "Goldman Sachs" "Credit Lyonnais" "Cohen and Co." "First Albany" "RBC" "Lazard" "SCO" "Soundview" "TD Securities" "Bank of America" "Barclays" "Deutsche Bank" "'
		
	local n: word count `replace_list'
	forvalues i = 1/`n' {
		local a: word `i' of `replace_list'
		local b: word `i' of `new_list'
		replace bookrunners = subinstr(bookrunners,"`a'","`b'",.) ///
			if regexm(bookrunners,"`a'/") | regexm(bookrunners,"`a'$")
	}

	replace bookrunners = subinstr(bookrunners,"Bank Of America","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of America Ca","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americaap","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americaa","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bank of Americav","Bank of America",.)
	replace bookrunners = subinstr(bookrunners,"Bnpparibas Asia","BNP Paribas",.)
	replace bookrunners = subinstr(bookrunners,"First RBC","First Dominion",.)
	replace bookrunners = subinstr(bookrunners,"RBCinion","First Dominion",.)
	replace bookrunners = subinstr(bookrunners,"Dbsecu","Deutsche Bank",.)
	replace bookrunners = subinstr(bookrunners,"Piperaffray","Piper Jaffray",.)


end
/*
*For now, we will do them live
use "$data_path/sdc_equity_clean", clear
br issuer date_daily bookrunners all_managers bookrunner_* if regex(all_managers,"Deutsche Banc Alex Brown")

import delimited using "$data_path/sdc_equity_issuance_all.csv", varnames(1) clear
standardize_bookrunners
split bookrunners, gen(bookrunner_) parse("/")
sort bookrunner_1
bys bookrunner_1: gen N = _N
br all_managers bookrunner_1 if N<5
